#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 1.9.{build}.0

environment:
  powershellgallery_api_token:
    secure: QFMDktDREWbxRj3h74Bud1xZI7FDti2aCIqwAj1l46RjPxH/tKOXp5+/IQVpXi9L

install: 
  - cinst -y pester
  - git clone https://github.com/PowerShell/DscResource.Tests
  - ps: Push-Location
  - cd DscResource.Tests
  - ps: Import-Module .\TestHelper.psm1 -force
  - ps: Pop-Location

#---------------------------------# 
#      build configuration        # 
#---------------------------------# 

build: false

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }
    
#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 

# scripts to run before deployment 
deploy_script: 
  - ps: |
      # Publish to PowerShell Gallery on tag
      if ($env:APPVEYOR_REPO_TAG -eq $true)
      {
        Write-Host "Publishing $env:APPVEYOR_PROJECT_NAME to PowerShellGallery"
        $projectUri = "https://github.com/PowerShell/$env:APPVEYOR_PROJECT_NAME"
        $licenseUri = "https://github.com/PowerShell/$env:APPVEYOR_PROJECT_NAME/blob/master/LICENSE"
        $tag = 'DesiredStateConfiguration DSC DSCResourceKit'
        Publish-Module -Name $env:APPVEYOR_PROJECT_NAME -ProjectUri $projectUri -LicenseUri $licenseUri -Tag $tag -NuGetApiKey $env:powershellgallery_api_token -verbose
      }
      
      # Creating project artifact
      $stagingDirectory = (Resolve-Path ..).Path
      
      Write-Host "TODO stagingDirectory = $stagingDirectory; projectUri = $projectUri; licenseUri = $licenseUri; tag = $tag; powershellgallery_api_token= $env:powershellgallery_api_token"
      
      $manifest = Join-Path $pwd "xTimeZone.psd1"
      (Get-Content $manifest -Raw).Replace("1.9.0.0", $env:APPVEYOR_BUILD_VERSION) | Out-File $manifest
      $zipFilePath = Join-Path $stagingDirectory "$(Split-Path $pwd -Leaf).zip"
      Add-Type -assemblyname System.IO.Compression.FileSystem
      [System.IO.Compression.ZipFile]::CreateFromDirectory($pwd, $zipFilePath)
      
      # Creating NuGet package artifact
      New-Nuspec -packageName $env:APPVEYOR_PROJECT_NAME -version $env:APPVEYOR_BUILD_VERSION -author "Microsoft" -owners "Microsoft" -licenseUrl "https://github.com/PowerShell/DscResources/blob/master/LICENSE" -projectUrl "https://github.com/$($env:APPVEYOR_REPO_NAME)" -packageDescription $env:APPVEYOR_PROJECT_NAME -tags "DesiredStateConfiguration DSC DSCResourceKit" -destinationPath .
      nuget pack ".\$($env:APPVEYOR_PROJECT_NAME).nuspec" -outputdirectory .
      $nuGetPackageName = $env:APPVEYOR_PROJECT_NAME + "." + $env:APPVEYOR_BUILD_VERSION + ".nupkg"
      $nuGetPackagePath = (Get-ChildItem $nuGetPackageName).FullName
      
      @(
          # You can add other artifacts here
          $zipFilePath,
          $nuGetPackagePath
      ) | % { 
          Write-Host "Pushing package $_ as Appveyor artifact"
          Push-AppveyorArtifact $_
        }
        


